version: "3.9"

services:
  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "8000:5000"
    environment:
      - SERVICE_B_URL=http://service_b:5001
    depends_on:
      - service_b

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "8001:5001"
